/** Generated Arabic copy for remaining page text; keys are exact English source strings. */
export const extraCopy: Record<string, string> = {
  "10 years": "١٠ سنوات",
  "14 days": "١٤ يوماً",
  "5 out of 5 stars": "٥ من ٥ نجوم",
  "A short placeholder excerpt. Replace with a real article about materials and finishes.": "مقتطف قصير مؤقت. يُستبدل بمقال فعلي عن المواد والتشطيبات.",
  "A short placeholder excerpt. Replace with a real article about our installation process.": "مقتطف قصير مؤقت. يُستبدل بمقال فعلي عن مراحل التركيب لدينا.",
  "A short placeholder excerpt. Replace with a real article about planning fitted storage.": "مقتطف قصير مؤقت. يُستبدل بمقال فعلي عن تخطيط وحدات التخزين المدمجة.",
  "A tailored price scope follows by your preferred contact method.": "سنرسل إليك تقديراً للتكلفة يناسب متطلباتك عبر وسيلة التواصل التي تفضّلها.",
  "Arabic Wardrobes": "خزائن ملابس بطابع عربي",
  "Arabic Wardrobes — الصورة ستُضاف قريباً": "خزائن ملابس بطابع عربي — الصورة ستُضاف قريباً",
  "Article cover image (client to supply)": "صورة غلاف المقال (يوفّرها العميل)",
  "Bathroom Vanity Units": "وحدات مغاسل الحمّامات",
  "Bathroom Vanity Units — الصورة ستُضاف قريباً": "وحدات مغاسل الحمّامات — الصورة ستُضاف قريباً",
  "Bathroom vanities designed around your basin, storage needs and room dimensions.": "وحدات مغاسل حمّامات مصمّمة لتناسب حوض المغسلة واحتياجات التخزين وأبعاد الحمّام.",
  "Bespoke Joinery services": "خدمات الأعمال الخشبية حسب الطلب",
  "Bespoke Living Room & Media Storage Units": "وحدات لغرف المعيشة والأجهزة الترفيهية حسب الطلب",
  "Bespoke Living Room & Media Storage Units — الصورة ستُضاف قريباً": "وحدات لغرف المعيشة والأجهزة الترفيهية حسب الطلب — الصورة ستُضاف قريباً",
  "Bespoke joinery": "أعمال خشبية حسب الطلب",
  "Boards, hardware and finishes chosen for Dubai's climate and for decades of daily use.": "ألواح وإكسسوارات وتشطيبات مختارة لتلائم مناخ دبي وتتحمّل الاستخدام اليومي لعقود.",
  "Breadcrumb": "مسار التصفّح",
  "Browse our work while you wait": "تصفّح أعمالنا أثناء الانتظار",
  "Built-in Wardrobes": "خزائن ملابس مدمجة",
  "Built-in Wardrobes — الصورة ستُضاف قريباً": "خزائن ملابس مدمجة — الصورة ستُضاف قريباً",
  "Built-in bookcases and home libraries planned around your collection and your room.": "خزائن كتب مدمجة ومكتبات منزلية مصمّمة لتناسب مجموعتك ومساحة غرفتك.",
  "Cabinets & Vanities services": "خدمات الخزائن ووحدات المغاسل",
  "Choose slide": "اختر شريحة",
  "Client name": "اسم العميل",
  "Concept imagery is illustrative and not a photograph of completed client work. Please confirm product specifications and availability with our team.": "صور التصاميم التصوّرية للتوضيح فقط، وليست صوراً لأعمال منجزة لعملائنا. يُرجى التأكّد من مواصفات المنتجات وتوافرها مع فريقنا.",
  "Custom Cabinets & Bespoke Vanity Units Dubai": "خزائن ووحدات مغاسل حسب الطلب في دبي",
  "Custom Cabinets & Bespoke Vanity Units Dubai — الصورة ستُضاف قريباً": "خزائن ووحدات مغاسل حسب الطلب في دبي — الصورة ستُضاف قريباً",
  "Custom Furniture": "أثاث حسب الطلب",
  "Custom Furniture — الصورة ستُضاف قريباً": "أثاث حسب الطلب — الصورة ستُضاف قريباً",
  "Custom Kitchen Design & Laundry Room Joinery": "تصميم مطابخ وأعمال خشبية لغرف الغسيل حسب الطلب",
  "Custom Kitchen Design & Laundry Room Joinery — الصورة ستُضاف قريباً": "تصميم مطابخ وأعمال خشبية لغرف الغسيل حسب الطلب — الصورة ستُضاف قريباً",
  "Custom Wardrobes & Luxury Closets Dubai": "خزائن ملابس حسب الطلب وغرف ملابس فاخرة في دبي",
  "Custom Wardrobes & Luxury Closets Dubai — الصورة ستُضاف قريباً": "خزائن ملابس حسب الطلب وغرف ملابس فاخرة في دبي — الصورة ستُضاف قريباً",
  "Custom storage for shoes and everyday essentials, fitted to your entryway or bedroom.": "وحدات تخزين للأحذية والمستلزمات اليومية، مصمّمة حسب الطلب لتناسب مدخل منزلك أو غرفة نومك.",
  "Custom wardrobes in Dubai — تفصيل خزائن دبي وتفصيل كبتات دبي — with layouts and finishes shaped around your home.": "خزائن ملابس حسب الطلب في دبي — تفصيل خزائن دبي وتفصيل كبتات دبي — بتقسيمات وتشطيبات مصمّمة لتناسب منزلك.",
  "Dark mode": "الوضع الداكن",
  "Describe the occasion and the pieces hanging in your wardrobe — our stylist will suggest an outfit from what you already own.": "صِف المناسبة والقطع الموجودة في خزانتك، وسيقترح منسّق الأزياء لدينا إطلالة من ملابسك الحالية.",
  "Discreet joinery solutions that make rooms work harder without compromising their character.": "حلول خشبية مدمجة بعناية تعزّز الاستفادة من الغرف دون المساس بطابعها.",
  "Do you offer a warranty?": "هل تقدّمون ضماناً؟",
  "Draft information pending review by Etherial Interiors. Please contact us for the current official policy.": "هذه المعلومات مسوّدة بانتظار مراجعة Etherial Interiors. يُرجى التواصل معنا للاطّلاع على السياسة الرسمية السارية.",
  "Draft information pending review by Etherial Interiors. Please contact us for the current official terms before commissioning work.": "هذه المعلومات مسوّدة بانتظار مراجعة Etherial Interiors. يُرجى التواصل معنا للاطّلاع على الشروط الرسمية السارية قبل التعاقد على تنفيذ الأعمال.",
  "ETHERIAL": "ETHERIAL",
  "ETHERIAL.": "ETHERIAL.",
  "Email address for newsletter": "البريد الإلكتروني للاشتراك في النشرة البريدية",
  "English": "الإنجليزية",
  "Etherial Interiors began with a simple frustration: beautiful joinery in Dubai took too long, cost too much, and too often arrived as a compromise. So we built our own workshop in Umm Ramool and kept everything — design, manufacture, installation — under one roof.": "بدأت حكاية Etherial Interiors من مشكلة واضحة: كانت الأعمال الخشبية الجميلة في دبي تستغرق وقتاً طويلاً، وتكلّف الكثير، وغالباً ما تأتي دون مستوى التطلّعات. لذلك أنشأنا ورشتنا الخاصة في أم رمول، وجمعنا كل المراحل — التصميم والتصنيع والتركيب — تحت سقف واحد.",
  "Etherial Interiors home": "الصفحة الرئيسية لـ Etherial Interiors",
  "Etherial Interiors, Dubai. All rights reserved.": "Etherial Interiors، دبي. جميع الحقوق محفوظة.",
  "Explore our wardrobes": "اكتشف خزائن الملابس لدينا",
  "Explore walk-in closet layouts, storage zones and finishes tailored to your space in Dubai.": "اكتشف تصاميم غرف الملابس وتقسيمات التخزين والتشطيبات المصمّمة خصيصاً لمساحتك في دبي.",
  "Facebook": "Facebook",
  "Fitted closet, Dubai": "خزانة ملابس مدمجة، دبي",
  "Fitted cupboards, shelving and work surfaces to organise your laundry room.": "خزائن ورفوف وأسطح عمل مصمّمة على المقاس لتنظيم غرفة الغسيل.",
  "Fitted wardrobes designed to make use of every available wall and corner.": "خزائن ملابس مدمجة مصمّمة للاستفادة من كل جدار وزاوية متاحة.",
  "Footer company": "روابط الشركة في تذييل الصفحة",
  "Footer portfolio": "روابط معرض الأعمال في تذييل الصفحة",
  "Furniture designed for your space, from the initial dimensions to the finishing details.": "أثاث مصمّم لمساحتك، من القياسات الأولية إلى أدقّ تفاصيل التشطيب.",
  "Google Maps embed — Umm Ramool location (embed URL to be supplied)": "خريطة Google مضمّنة — موقع أم رمول (سيُوفَّر رابط التضمين لاحقاً)",
  "Hidden Doors & Wall Beds": "أبواب مخفية وأسرّة جدارية قابلة للطي",
  "Hidden Doors & Wall Beds — الصورة ستُضاف قريباً": "أبواب مخفية وأسرّة جدارية قابلة للطي — الصورة ستُضاف قريباً",
  "How do I request an estimate?": "كيف أطلب تقديراً للتكلفة؟",
  "Individual pieces and architectural woodwork made to suit the proportions and character of your home.": "قطع أثاث منفردة وأعمال خشبية معمارية مصنوعة لتناسب أبعاد منزلك وطابعه.",
  "Information you provide": "المعلومات التي تقدّمها",
  "Instagram": "Instagram",
  "Interior design concepts": "تصوّرات التصميم الداخلي",
  "Items in your wardrobe": "القطع الموجودة في خزانتك",
  "Kitchen & Laundry services": "خدمات المطابخ وغرف الغسيل",
  "Kitchen, Dubai": "مطبخ، دبي",
  "Laundry Room Storage": "وحدات تخزين لغرف الغسيل",
  "Laundry Room Storage — الصورة ستُضاف قريباً": "وحدات تخزين لغرف الغسيل — الصورة ستُضاف قريباً",
  "Libraries & Bookcases": "مكتبات وخزائن كتب",
  "Libraries & Bookcases — الصورة ستُضاف قريباً": "مكتبات وخزائن كتب — الصورة ستُضاف قريباً",
  "Living & Media Storage services": "خدمات وحدات التخزين لغرف المعيشة والأجهزة الترفيهية",
  "Living space, Dubai": "مساحة معيشة، دبي",
  "Luxury Kitchens": "مطابخ فاخرة",
  "Luxury Kitchens — الصورة ستُضاف قريباً": "مطابخ فاخرة — الصورة ستُضاف قريباً",
  "Made-to-measure cupboards and cabinet installation for the rooms of your home.": "تفصيل وتركيب خزائن على المقاس لمختلف غرف منزلك.",
  "Made-to-measure kitchen cabinetry and storage designed around how you cook and gather.": "خزائن مطبخ ووحدات تخزين على المقاس، مصمّمة لتناسب أسلوبك في الطهي واجتماع الأهل والأصدقاء.",
  "Made-to-measure wardrobes and closets planned around the space you have and the way you live. Explore the options below for your Dubai home.": "خزائن وغرف ملابس على المقاس، مصمّمة لتناسب مساحتك وأسلوب حياتك. اكتشف الخيارات أدناه لمنزلك في دبي.",
  "Media wall joinery with room for screens, equipment, display and concealed storage.": "وحدات جدارية خشبية تضمّ مساحات للشاشات والأجهزة والعرض، مع تخزين مخفي.",
  "Mon–Fri 9:00–18:00 · Sat 9:00–19:00": "الاثنين–الجمعة ٩:٠٠–١٨:٠٠ · السبت ٩:٠٠–١٩:٠٠",
  "Next image": "الصورة التالية",
  "Notifications alt+T": "الإشعارات alt+T",
  "Open menu": "فتح القائمة",
  "Pause slideshow": "إيقاف عرض الشرائح مؤقتاً",
  "Placeholder article — choosing kitchen materials for Dubai's climate": "مقال مؤقت — اختيار مواد المطابخ المناسبة لمناخ دبي",
  "Placeholder article — how to plan a fitted closet": "مقال مؤقت — كيفية تخطيط خزانة ملابس مدمجة",
  "Placeholder article — what a 14-day fit-out actually looks like": "مقال مؤقت — كيف تسير أعمال التجهيز الداخلي خلال ١٤ يوماً على أرض الواقع",
  "Placeholder link — the client's Google review URL will be added here.": "رابط مؤقت — سيُضاف هنا رابط تقييم العميل على Google.",
  "Placeholder review — replace with a real client testimonial about their fitted closet project.": "تقييم مؤقت — يُستبدل بشهادة حقيقية من عميل عن مشروع خزانة ملابسه المدمجة.",
  "Placeholder review — replace with a real client testimonial about their kitchen renovation.": "تقييم مؤقت — يُستبدل بشهادة حقيقية من عميل عن تجديد مطبخه.",
  "Placeholder review — replace with a real client testimonial about their living space joinery.": "تقييم مؤقت — يُستبدل بشهادة حقيقية من عميل عن الأعمال الخشبية في مساحة معيشته.",
  "Practical fitted joinery for the rooms you use every day, shaped around your routines and available space.": "أعمال خشبية مدمجة وعملية للغرف التي تستخدمها يومياً، مصمّمة لتناسب روتينك ومساحتك المتاحة.",
  "Prefer to talk first? Pick a time that suits you and meet our design team.": "تفضّل التحدّث معنا أولاً؟ اختر الوقت المناسب لك والتقِ بفريق التصميم لدينا.",
  "Premium Bespoke Joinery Services in Dubai": "خدمات أعمال خشبية فاخرة حسب الطلب في دبي",
  "Premium Bespoke Joinery Services in Dubai — الصورة ستُضاف قريباً": "خدمات أعمال خشبية فاخرة حسب الطلب في دبي — الصورة ستُضاف قريباً",
  "Previous image": "الصورة السابقة",
  "Primary": "التنقّل الرئيسي",
  "Project photographs": "صور المشاريع",
  "Purpose-built cabinetry and vanities that bring order to the details of daily life.": "خزائن ووحدات مغاسل مصمّمة خصيصاً لاحتياجاتك، لتنظيم تفاصيل حياتك اليومية.",
  "Questions about these terms? Email": "لديك أسئلة حول هذه الشروط؟ راسلنا على",
  "Residential Cabinets": "خزائن منزلية",
  "Residential Cabinets — الصورة ستُضاف قريباً": "خزائن منزلية — الصورة ستُضاف قريباً",
  "Shoe Cabinets & Dressers": "خزائن أحذية ووحدات أدراج",
  "Shoe Cabinets & Dressers — الصورة ستُضاف قريباً": "خزائن أحذية ووحدات أدراج — الصورة ستُضاف قريباً",
  "Show Bespoke kitchens": "عرض المطابخ المصمّمة حسب الطلب",
  "Show Fitted closets": "عرض خزائن الملابس المدمجة",
  "Show Living spaces": "عرض مساحات المعيشة",
  "Sliding Doors & Closets": "أبواب وخزائن ملابس منزلقة",
  "Sliding Doors & Closets — الصورة ستُضاف قريباً": "أبواب وخزائن ملابس منزلقة — الصورة ستُضاف قريباً",
  "Social media profiles": "حسابات التواصل الاجتماعي",
  "Space-conscious sliding doors and reach-in closet storage, designed to fit your room.": "أبواب منزلقة وخزائن ملابس تُفتح من الخارج، مصمّمة لتوفير المساحة وتناسب غرفتك.",
  "Storage and display joinery that makes living spaces feel considered, calm and personal.": "وحدات خشبية للتخزين والعرض تضفي على مساحات المعيشة تناغماً وهدوءاً وطابعاً شخصياً.",
  "Submitting an enquiry does not constitute an order or a binding quotation. Project scope, pricing, timelines, payment arrangements and warranty coverage should be confirmed directly with Etherial Interiors in writing before work begins.": "لا يُعدّ إرسال استفسار طلب شراء أو عرض سعر ملزماً. يجب تأكيد نطاق المشروع والأسعار والجداول الزمنية وترتيبات الدفع وتغطية الضمان خطياً ومباشرةً مع Etherial Interiors قبل بدء العمل.",
  "Suggest an outfit": "اقترح إطلالة",
  "Switch to English": "التبديل إلى الإنجليزية",
  "Switch to dark mode": "التبديل إلى الوضع الداكن",
  "TV Wall Units": "وحدات تلفزيون جدارية",
  "TV Wall Units — الصورة ستُضاف قريباً": "وحدات تلفزيون جدارية — الصورة ستُضاف قريباً",
  "The occasion": "المناسبة",
  "The people who measure your home are the people who build and fit your joinery.": "الفريق الذي يأخذ قياسات منزلك هو نفسه الذي يصنّع أعمالك الخشبية ويركّبها.",
  "The quote form asks for your name, email, phone number and project details. The newsletter form asks for your email address. Form entries are saved in your browser on this device; if a submission service is configured, they may also be sent to that service.": "يطلب نموذج عرض السعر اسمك وبريدك الإلكتروني ورقم هاتفك وتفاصيل مشروعك. ويطلب نموذج الاشتراك في النشرة البريدية عنوان بريدك الإلكتروني. تُحفظ البيانات المُدخلة في النماذج داخل متصفّحك على هذا الجهاز؛ وإذا جرى إعداد خدمة لإرسال النماذج، فقد تُرسل البيانات إلى تلك الخدمة أيضاً.",
  "TikTok": "TikTok",
  "Today we've completed more than 500 fit-outs across the city, each one measured, crafted and installed by our own team, and each one covered by a 10-year warranty.": "أنجزنا حتى اليوم أكثر من ٥٠٠ مشروع تجهيز داخلي في مختلف أنحاء المدينة، تولّى فريقنا قياسات كلٍّ منها وتصنيعه وتركيبه، وجميعها مشمولة بضمان لمدة ١٠ سنوات.",
  "Umm Ramool, Dubai, UAE": "أم رمول، دبي، الإمارات العربية المتحدة",
  "Walk-in Closet Design": "تصميم غرف الملابس",
  "Walk-in Closet Design — الصورة ستُضاف قريباً": "تصميم غرف الملابس — الصورة ستُضاف قريباً",
  "Want a wardrobe that keeps every piece in view?": "هل تريد خزانة ملابس تُبقي كل قطعة أمام عينيك؟",
  "Wardrobe stylist": "منسّق إطلالاتك",
  "Wardrobes & Closets services": "خدمات خزائن وغرف الملابس",
  "We quote a date and we keep it — 99.4% of our installations finish on time.": "نحدّد موعداً ونلتزم به — نُنجز ٩٩٫٤٪ من أعمال التركيب في موعدها.",
  "We visit, measure, and your build begins — typically fitted within 14 days.": "نزورك ونأخذ القياسات، ثم نبدأ التصنيع — وعادةً ما يكتمل التركيب خلال ١٤ يوماً.",
  "Website content": "محتوى الموقع الإلكتروني",
  "Website enquiries": "استفسارات الموقع الإلكتروني",
  "What can you make?": "ما الذي يمكنكم تصنيعه؟",
  "What should I wear?": "ماذا أرتدي؟",
  "Where are you based?": "أين مقرّكم؟",
  "Workshop or team photograph (client to supply)": "صورة للورشة أو الفريق (يوفّرها العميل)",
  "You can clear stored form entries using your browser’s site-data controls. To ask about your information or newsletter subscription, write to": "يمكنك حذف بيانات النماذج المحفوظة من خلال إعدادات بيانات المواقع في متصفّحك. للاستفسار عن معلوماتك أو اشتراكك في النشرة البريدية، راسلنا على",
  "Your booking confirmation is on its way to your inbox. If you need to change the time, just reply to that email.": "رسالة تأكيد حجزك في طريقها إلى بريدك الإلكتروني. إذا احتجت إلى تغيير الموعد، فما عليك سوى الردّ على الرسالة.",
  "Your choices": "خياراتك",
  "Your details land with our design team immediately.": "تصل بياناتك إلى فريق التصميم لدينا فوراً.",
  "Your personalised outfit will appear here.": "ستظهر هنا الإطلالة المنسّقة خصيصاً لك.",
  "Your recommendation": "اقتراحنا لك",
  "bespoke joinery": "أعمال خشبية حسب الطلب",
  "cabinets & vanities": "خزائن ووحدات مغاسل",
  "e.g. Evening wedding reception in Jumeirah": "مثال: حفل زفاف مسائي في جميرا",
  "e.g. navy linen suit, white shirt, tan loafers, silk scarf, gold watch": "مثال: بدلة كتان كحلية، قميص أبيض، حذاء لوفر بني فاتح، وشاح حريري، ساعة ذهبية",
  "info@etherial.ae": "info@etherial.ae",
  "kitchen & laundry": "مطابخ وغرف غسيل",
  "living & media storage": "وحدات تخزين لغرف المعيشة والأجهزة الترفيهية",
  "wardrobes & closets": "خزائن وغرف ملابس"
};
