/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SectionRouteImport } from './routes/$section'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BookingCompleteRouteImport } from './routes/booking-complete'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as SectionServiceRouteImport } from './routes/$section.$service'
import { Route as PortfolioIndexRouteImport } from './routes/portfolio/index'
import { Route as PortfolioCategoryRouteImport } from './routes/portfolio/$category'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionRoute = SectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingCompleteRoute = BookingCompleteRouteImport.update({
  id: '/booking-complete',
  path: '/booking-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionServiceRoute = SectionServiceRouteImport.update({
  id: '/$service',
  path: '/$service',
  getParentRoute: () => SectionRoute,
} as any)
const PortfolioIndexRoute = PortfolioIndexRouteImport.update({
  id: '/portfolio/',
  path: '/portfolio/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioCategoryRoute = PortfolioCategoryRouteImport.update({
  id: '/portfolio/$category',
  path: '/portfolio/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$section': typeof SectionRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/booking-complete': typeof BookingCompleteRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/$section/$service': typeof SectionServiceRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$section': typeof SectionRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/booking-complete': typeof BookingCompleteRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/$section/$service': typeof SectionServiceRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
  '/portfolio': typeof PortfolioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$section': typeof SectionRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/booking-complete': typeof BookingCompleteRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/$section/$service': typeof SectionServiceRoute
  '/portfolio/$category': typeof PortfolioCategoryRoute
  '/portfolio/': typeof PortfolioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$section'
    | '/about'
    | '/blog'
    | '/booking-complete'
    | '/contact'
    | '/faqs'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/$section/$service'
    | '/portfolio/$category'
    | '/portfolio/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$section'
    | '/about'
    | '/blog'
    | '/booking-complete'
    | '/contact'
    | '/faqs'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/$section/$service'
    | '/portfolio/$category'
    | '/portfolio'
  id:
    | '__root__'
    | '/'
    | '/$section'
    | '/about'
    | '/blog'
    | '/booking-complete'
    | '/contact'
    | '/faqs'
    | '/privacy-policy'
    | '/terms-and-conditions'
    | '/$section/$service'
    | '/portfolio/$category'
    | '/portfolio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SectionRoute: typeof SectionRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  BookingCompleteRoute: typeof BookingCompleteRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  PortfolioCategoryRoute: typeof PortfolioCategoryRoute
  PortfolioIndexRoute: typeof PortfolioIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section': {
      id: '/$section'
      path: '/$section'
      fullPath: '/$section'
      preLoaderRoute: typeof SectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-complete': {
      id: '/booking-complete'
      path: '/booking-complete'
      fullPath: '/booking-complete'
      preLoaderRoute: typeof BookingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$section/$service': {
      id: '/$section/$service'
      path: '/$service'
      fullPath: '/$section/$service'
      preLoaderRoute: typeof SectionServiceRouteImport
      parentRoute: typeof SectionRoute
    }
    '/portfolio/': {
      id: '/portfolio/'
      path: '/portfolio'
      fullPath: '/portfolio/'
      preLoaderRoute: typeof PortfolioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/$category': {
      id: '/portfolio/$category'
      path: '/portfolio/$category'
      fullPath: '/portfolio/$category'
      preLoaderRoute: typeof PortfolioCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SectionRouteChildren {
  SectionServiceRoute: typeof SectionServiceRoute
}

const SectionRouteChildren: SectionRouteChildren = {
  SectionServiceRoute: SectionServiceRoute,
}

const SectionRouteWithChildren =
  SectionRoute._addFileChildren(SectionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SectionRoute: SectionRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  BookingCompleteRoute: BookingCompleteRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  PortfolioCategoryRoute: PortfolioCategoryRoute,
  PortfolioIndexRoute: PortfolioIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
